# Generated by Django 3.0.7 on 2020-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rating',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='design_rating',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='usability_rating',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
